{"ast":null,"code":"function catchErrors(error, displayError) {\n  let errorMsg;\n\n  if (error.response) {\n    // The request was made and the server responsed with a status code that is not in the range of 2XX\n    errorMsg = error.response.data;\n    console.error(\"Error response\", errorMsg); // For Cloudinary image uploads\n\n    if (error.response.data.error) {\n      errorMsg = error.response.data.error.message;\n    }\n  } else if (error.request) {\n    // The request was made, but no response was received\n    errorMsg = error.request;\n    console.error(\"Error request\", errorMsg);\n  } else {\n    // Something else happened in making the request that triggered an error\n    errorMsg = error.message;\n    console.error(\"Error message\", errorMsg);\n  }\n\n  displayError(errorMsg);\n}\n\nexport default catchErrors;","map":null,"metadata":{},"sourceType":"module"}